AutoRepairShop.Web/Controllers/BackOffice/FuelsController.cs
using AutoRepairShop.Web.Data.Entities;
using AutoRepairShop.Web.Data.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace AutoRepairShop.Web.Controllers.BackOffice
{
    public class FuelsController : Controller
    {

        private readonly IFuelRepository _fuelRepository;

        public FuelsController(IFuelRepository fuelRepository)
        {

            _fuelRepository = fuelRepository;
        }

        // GET: Fuels
        [Authorize(Roles = "Employee/Management, Employee/Reception, Admin")]
        public IActionResult Index()
        {
            return View(_fuelRepository.GetAll().OrderBy(f => f.FuelType));
        }

        // GET: Fuels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fuel = await _fuelRepository
                .GetByIdAsync(id.Value);
            if (fuel == null)
            {
                return NotFound();
            }

            return View(fuel);
        }

        // GET: Fuels/Create
        [Authorize(Roles = "Employee/Management, Employee/Reception, Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fuels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Fuel fuel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    fuel.CreationDate = DateTime.UtcNow;
                    fuel.IsActive = true;
                    await _fuelRepository
                        .CreateAsync(fuel);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    if (ex.InnerException.Message.Contains("duplicate"))
                    {


                        ModelState.AddModelError(string.Empty, $"There is allready a Fuel registered with the name {fuel.FuelType} please insert another");
                        return View(fuel);

                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, ex.InnerException.Message);
                        return View(fuel);
                    }
                }

            }
            return View(fuel);
        }

        // GET: Fuels/Edit/5
        [Authorize(Roles = "Employee/Management, Employee/Reception, Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fuel = await _fuelRepository
                .GetByIdAsync(id.Value);
            if (fuel == null)
            {
                return NotFound();
            }
            return View(fuel);
        }

        // POST: Fuels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Fuel fuel)
        {


            if (ModelState.IsValid)
            {
                try
                {

                    try
                    {
                        fuel.UpdateDate = DateTime.UtcNow;
                        if (fuel.IsActive == false)
                        {
                            fuel.DeactivationDate = DateTime.UtcNow;
                        }
                        await _fuelRepository
                            .UpdateAsync(fuel);
                    }
                    catch (Exception ex)
                    {

                        if (ex.InnerException.Message.Contains("duplicate"))
                        {


                            ModelState.AddModelError(string.Empty, $"There is allready a Fuel registered with the name {fuel.FuelType} please insert another");

                            return View(fuel);
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, ex.InnerException.Message);
                            return View(fuel);
                        }
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _fuelRepository.ExistsAsync(fuel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fuel);
        }

        // GET: Fuels/Delete/5
        [Authorize(Roles = "Employee/Management, Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fuel = await _fuelRepository
                .GetByIdAsync(id.Value);
            if (fuel == null)
            {
                return NotFound();
            }

            return View(fuel);
        }

        // POST: Fuels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fuel = await _fuelRepository
                .GetByIdAsync(id);
            try
            {

                await _fuelRepository
                    .DeleteAsync(fuel);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                if (ex.InnerException.Message.Contains("REFERENCE constraint"))
                {

                    if (ModelState.IsValid)
                    {
                        //TODO make buttons to get to the respective views
                        ViewBag.Error = $"There are Vehicles associated with {fuel.FuelType}, so it can not be deleted, please deactivate";
                        return View(fuel);
                    }

                }
                else
                {
                    ModelState.AddModelError(string.Empty, ex.InnerException.Message);
                    return View(fuel);
                }
            }

            return View(fuel);
        }
    }
}

AutoRepairShop.Web/Views/Fuels/Create.cshtml
@model AutoRepairShop.Web.Data.Entities.Fuel
@{
    ViewData["Title"] = "Create Fuel";
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <div class="panel-body">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" asp-for="FuelType"></label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" id="inputDefault" asp-for="FuelType">
                        </div>
                        <span asp-validation-for="FuelType" class="text-warning"></span>
                    </div>


                    <div style="text-align: center">
                        <div class="form-group">
                            <button type="submit" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Add</button>
                            <a asp-action="Index" formnovalidate class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Exit</a>
                        </div>
                    </div>

                </form>
            </div>
        </section>


    </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoRepairShop.Web/Views/Fuels/Delete.cshtml
@model AutoRepairShop.Web.Data.Entities.Fuel

@{
    ViewData["Title"] = "Delete Fuel";
}


<h3>Are you sure you want to delete this?</h3>


<h2>@ViewBag.Error </h2>


<section class="panel">
    <div class="panel-body tab-content">
        <div id="access-log" class="tab-pane active">
            <table class="table table-striped table-no-more table-bordered  mb-none">
                <thead>
                    <tr>
                        <th style="width: 25%; margin: auto"><span class="text-normal text-sm">Data</span></th>
                        <th style="width: 55%"><span class="text-normal text-sm">Fuel Information</span></th>
                    </tr>
                </thead>
                <tbody class="log-viewer">
                    <tr>
                        <td data-title="Type" class="pt-md pb-md">
                            @Html.DisplayNameFor(model => model.FuelType)
                        </td>
                        <td data-title="Date" class="pt-md pb-md">
                            @Html.DisplayFor(model => model.FuelType)
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <form asp-action="Delete" style="text-align: center">
            <input type="hidden" asp-for="Id" />
            <button type="submit" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Delete</button>
            <a asp-action="Index" formnovalidate class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Exit</a>
        </form>

    </div>
</section>

AutoRepairShop.Web/Views/Fuels/Details.cshtml
@model AutoRepairShop.Web.Data.Entities.Fuel

@{
    ViewData["Title"] = "Fuel Details";
}


<div class="timeline">
    <div class="tm-body">
        <div class="inner-toolbar clearfix">
            <ul>
                <li class="right">
                    <ul class="nav nav-pills nav-pills-primary">
                        <li>
                            <label>Go to</label>
                        </li>
                        <li class="active">
                            <a asp-action="Edit" asp-route-id="@Model.Id" style="font-size: 15px">Edit</a>
                        </li>
                        <li>
                            <a asp-action="Index" style="font-size: 15px">Back to List</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="tm-title">
            <h3 class="h5 text-uppercase">Fuel info</h3>
        </div>
        <div style="text-align: center">

        </div>
        <ol class="tm-items">
            <li>
                <div class="tm-info">
                    <div class="tm-icon"><i class="fa fa-arrow-right"></i></div>
                    <time class="tm-datetime">
                        <div class="tm-datetime-time" style="font-size: 13px">@Html.DisplayNameFor(model => model.FuelType)</div>
                    </time>
                </div>
                <div>
                    <p style="font-size: 20px">
                        @Html.DisplayFor(model => model.FuelType)
                    </p>
                </div>
            </li>
            <li>
                <div class="tm-info">
                    <div class="tm-icon"><i class="fa fa-arrow-right"></i></div>
                    <time class="tm-datetime">
                        <div class="tm-datetime-time" style="font-size: 13px">@Html.DisplayNameFor(model => model.IsActive)</div>
                    </time>
                </div>
                <div>
                    <p style="font-size: 20px">
                        @Html.DisplayFor(model => model.IsActive)
                    </p>
                </div>
            </li>
            <li>
                <div class="tm-info">
                    <div class="tm-icon"><i class="fa fa-arrow-right"></i></div>
                    <time class="tm-datetime">
                        <div class="tm-datetime-time" style="font-size: 13px">@Html.DisplayNameFor(model => model.CreationDate)</div>
                    </time>
                </div>
                <div>
                    <p style="font-size: 20px">
                        @Html.DisplayFor(model => model.CreationDate)
                    </p>
                </div>
            </li>
            <li>
                <div class="tm-info">
                    <div class="tm-icon"><i class="fa fa-arrow-right"></i></div>
                    <time class="tm-datetime">
                        <div class="tm-datetime-time" style="font-size: 13px">@Html.DisplayNameFor(model => model.UpdateDate)</div>
                    </time>
                </div>
                <div>
                    <p style="font-size: 20px">
                        @Html.DisplayFor(model => model.UpdateDate)
                    </p>
                </div>
            </li>
            <li>
                <div class="tm-info">
                    <div class="tm-icon"><i class="fa fa-arrow-right"></i></div>
                    <time class="tm-datetime">
                        <div class="tm-datetime-time" style="font-size: 13px">@Html.DisplayNameFor(model => model.DeactivationDate)</div>
                    </time>
                </div>
                <div>
                    <p style="font-size: 20px">
                        @Html.DisplayFor(model => model.DeactivationDate)
                    </p>
                </div>
            </li>
        </ol>
    </div>
</div>

AutoRepairShop.Web/Views/Fuels/Edit.cshtml
@model AutoRepairShop.Web.Data.Entities.Fuel

@{
    ViewData["Title"] = "Edit Fuel";
}


<div class="row">
    <div class="col-lg-12">
        <section class="panel">

            <div class="panel-body">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" asp-for="FuelType"></label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" id="inputDefault" asp-for="FuelType">
                        </div>
                        <span asp-validation-for="FuelType" class="text-warning"></span>
                    </div>


                    <div style="text-align: center">
                        <div class="form-group">
                            <button type="submit" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Change</button>
                            <a asp-action="Index" formnovalidate class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Exit</a>
                            <button asp-action="Delete" asp-controller="Fuels" asp-route-id="Id" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Delete Fuel</button>
                        </div>
                    </div>

                </form>
            </div>
        </section>

    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoRepairShop.Web/Views/Fuels/Index.cshtml
@model IEnumerable<AutoRepairShop.Web.Data.Entities.Fuel>

@{
    ViewData["Title"] = "Fuels";
}


<section class="panel">
    <div class="panel-body">
        <div class="inner-toolbar clearfix">
            <ul>
                <li class="right">
                    <ul class="nav nav-pills nav-pills-primary">
                        <li>
                            <label>Go to</label>
                        </li>
                        <li>
                            <a asp-action="Create" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 250px">Create new Fuel</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

        <table class="table table-bordered table-striped mb-none" id="datatable-editable">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FuelType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CreationDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UpdateDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DeactivationDate)
                    </th>
                    <th>
                        Options
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FuelType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreationDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdateDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeactivationDate)
                    </td>

                    <td class="actions">
                        <a asp-action="Details" asp-route-id="@item.Id">  Details</a>
                        <a asp-action="Edit" asp-route-id="@item.Id">  Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">  Delete</a>
                    </td>
                </tr>
                }

            </tbody>
        </table>
    </div>
</section>