AutoRepairShop.Web/Models/ActiveScheduleViewModel/CompleteScheduleByDealershipNoUserViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AutoRepairShop.Web.Models.ActiveScheduleViewModel
{
    public class CompleteScheduleByDealershipNoUserViewModel
    {
        public string UserId { get; set; }


        public int VehicleId { get; set; }



        public int ServiceId { get; set; }



        public int DealershipId { get; set; }



        public string DaysToDisable { get; set; }


        [Required]
        public DateTime Day { get; set; }



        [MaxLength(500)]
        public string Remarks { get; set; }


        [Required]
        [MaxLength(10)]
        public string Mileage { get; set; }
    }
}

AutoRepairShop.Web/Models/ActiveScheduleViewModel/CompleteScheduleViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AutoRepairShop.Web.Models.ActiveScheduleViewModel
{
    public class CompleteScheduleViewModel
    {

        public int VehicleId { get; set; }


        public int ServiceId {get; set; }


        public int ServicesSuppliedId { get; set; }



        public int DealershipId { get; set; }



        public string DaysToDisable { get; set; }


        [Required]
        public DateTime Day { get; set; }



        [MaxLength(500)]
        public string Remarks { get; set; }


        [Required]
        [MaxLength(10)]
        public string Mileage { get; set; }
    }
}

AutoRepairShop.Web/Models/ActiveScheduleViewModel/DeleteScheduleViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AutoRepairShop.Web.Models.ActiveScheduleViewModel
{
    public class DeleteScheduleViewModel
    {

        public int ActiveScheduleId { get; set; }



        [Display(Name = "Licence Plate")]
        public string LicencePLate { get; set; }



        public string Dealership { get; set; }




        public string Service { get; set; }



        [Display(Name = "Schedule Day")]
        public DateTime ScheduleDay { get; set; }


    }
}

AutoRepairShop.Web/Models/ActiveScheduleViewModel/EditScheduleViewModel.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AutoRepairShop.Web.Models.ActiveScheduleViewModel
{
    public class EditScheduleViewModel
    {
        public int ActiveScheduleId { get; set; }

        [Display(Name ="Licence Plate")]
        public string LicencePlate { get; set; }


        public string Dealership { get; set; }

        [Display(Name ="Services")]
        public int ServicesSupliedId { get; set; }


        public IEnumerable<SelectListItem> Services { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        public DateTime Day { get; set; }


        public string Remarks { get; set; }


        public string DaysToDisable { get; set; }
    }
}

AutoRepairShop.Web/Models/ActiveScheduleViewModel/ScheduleDetailsViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AutoRepairShop.Web.Models.ActiveScheduleViewModel
{
    public class ScheduleDetailsViewModel
    {
        public int ActiveScheduleId { get; set; }


        [Display(Name ="Licence Plate")]
        public string LicencePLate { get; set; }

       
        
        public string Brand { get; set; }

        
        
        public string Model { get; set; }

        
        
        public string Mileage { get; set; }

        
        
        public string Dealership { get; set; }

        
        
        public string Service { get; set; }
        
        
        
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        public DateTime Date { get; set; }

        
        
        
        public string Remarks { get; set; }

    }
}

AutoRepairShop.Web/Controllers/BackAndFrontOffice/ScheduleDetailsController.cs
using AutoRepairShop.Web.Data.Repositories.Interfaces;
using AutoRepairShop.Web.Helpers.Interfaces;
using AutoRepairShop.Web.Models.ActiveScheduleViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.VisualStudio.Web.CodeGeneration;
using Syncfusion.EJ2;
using Syncfusion.EJ2.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoRepairShop.Web.Controllers.BackAndFrontOffice
{
    public class ScheduleDetailsController : Controller
    {
        private readonly IActiveScheduleRepository _activeScheduleRepository;
        private readonly IUserHelper _userHelper;
        private readonly IVehicleRepository _vehicleRepository;
        private readonly IServicesSuppliedRepository _servicesSuppliedRepository;
        private readonly IConverterHelper _converterHelper;
        private readonly IDealershipRepository _dealershipRepository;
        private readonly IScheduleDetailRepository _scheduleDetailRepository;
        private readonly IServiceRepository _serviceRepository;
        private readonly IEmployeeRepository _employeeRepository;

        public ScheduleDetailsController(IActiveScheduleRepository activeScheduleRepository,
            IUserHelper userHelper,
            IVehicleRepository vehicleRepository,
            IServicesSuppliedRepository servicesSuppliedRepository,
            IConverterHelper converterHelper,
            IDealershipRepository dealershipRepository,
            IScheduleDetailRepository scheduleDetailRepository,
            IServiceRepository serviceRepository,
            IEmployeeRepository employeeRepository)
        {
            _activeScheduleRepository = activeScheduleRepository;
            _userHelper = userHelper;
            _vehicleRepository = vehicleRepository;
            _servicesSuppliedRepository = servicesSuppliedRepository;
            _converterHelper = converterHelper;
            _dealershipRepository = dealershipRepository;
            _scheduleDetailRepository = scheduleDetailRepository;
            _serviceRepository = serviceRepository;
            _employeeRepository = employeeRepository;
        }


        
        public async Task<IActionResult> Index()
        {

            var userName = this.User.Identity.Name;

            var user = await _userHelper.GetUserByEmailAsync(userName);


            if (user.IsActive == false)
            {
                return RedirectToAction("EditUser", "Accounts");
            }

            var ScheduleDetail = _scheduleDetailRepository.GetSchedulesDetail(user.Id);



            return View(ScheduleDetail);
        }

        [Authorize(Roles = "Employee/Management, Employee/Reception, Admin, Customer")]
        public async Task<IActionResult> BeginNew()
        {


            var userName = this.User.Identity.Name;

            var user = await _userHelper.GetUserByEmailAsync(userName);


            if (user.IsActive == false)
            {
                return RedirectToAction("EditUser", "Accounts");
            }

            var services = _serviceRepository.GetAllServices();


            var vehicles = _vehicleRepository.GetUserVehicles(user.Id);



            var model = _converterHelper.ToNewScheduleViewModel(vehicles, services);
            if (vehicles.ToList().Count == 0)
            {

                ViewBag.NoVehicles = "No cars, send back";
                return View(model);
            }

            return View(model);

        }




        [HttpPost]
        public async Task<IActionResult> BeginNew(BeginScheduleViewModel model)
        {

            if (ModelState.IsValid)
            {
                var service = await _servicesSuppliedRepository.GetService(model.ServicesSuppliedId);

                if (!await _scheduleDetailRepository.IsDuplicatedSchedulesForSameServiceAsync(model.VehicleId, model.ServicesSuppliedId))
                {
                    return RedirectToAction("CompleteSchedule", model);
                }
                else
                {
                    var services = _serviceRepository.GetAllServices();

                    var userName = this.User.Identity.Name;

                    var user = await _userHelper.GetUserByEmailAsync(userName);

                    var vehicles = _vehicleRepository.GetUserVehicles(user.Id);
                    var returnModel = _converterHelper.ToNewScheduleViewModel(vehicles, services);
                    ViewBag.ServiceDuplicated = $"There is already a schedule registered for {service.Service.ServiceType}, please chose another or change the current schedule";
                    return View(returnModel);
                }

            }

            return View(model);
        }

        [Authorize(Roles = "Employee/Management, Employee/Reception, Admin, Customer")]
        public async Task<IActionResult> CompleteSchedule(BeginScheduleViewModel model)
        {

            var service = await _servicesSuppliedRepository.GetService(model.ServicesSuppliedId);
            var newModel = _converterHelper.ToCompleteScheduleViewModel(model, service.Service);
            var list = await GetDisabledDaysAsync(model.ServicesSuppliedId, model.DealershipId);
            var days = Newtonsoft.Json.JsonConvert.SerializeObject(list);
            newModel.DaysToDisable = days;

            return View(newModel);
        }

        [HttpPost]
        public async Task<ActionResult> CompleteSchedule(CompleteScheduleViewModel model)
        {
            if (ModelState.IsValid)
            {

                var service = await _serviceRepository.GetByIdAsync(model.ServiceId);
                var activeSchedule = _converterHelper.ToActiveSchedule(model, service);
                var vehicle = await _vehicleRepository.GetByIdAsync(model.VehicleId);
                var dealership = await _dealershipRepository.GetByIdAsync(model.DealershipId);

                var scheduleDetail = _converterHelper.ToScheduleDetail(vehicle, activeSchedule, dealership);


                try
                {
                    await _scheduleDetailRepository.CreateAsync(scheduleDetail);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    if (ex.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "There is already a schedule for that service");
                        return View(model);
                    }

                }

            }
            return View(model);
        }

       
        public async Task<JsonResult> GetDealershipByService(int serviceId)
        {
            var dealership = await _servicesSuppliedRepository.GetDealershipsByServicesasync(serviceId);


            return this.Json(dealership);

        }

        /// <summary>
        /// This method checks if the number of schedules by service per a specific dealership is full and disables dates in View
        /// </summary>
        /// <param name="servicesSuppliedId"></param>
        /// <param name="dealershipId"></param>
        /// <returns>a List of dates to be disabled</returns>
        public async Task<List<DateTime>> GetDisabledDaysAsync(int servicesSuppliedId, int dealershipId)
        {
            var list = await _activeScheduleRepository.GetDaysByServiceId(servicesSuppliedId);

            List<DateTime> days = new List<DateTime>();

            var services = await _servicesSuppliedRepository.GetDealershipServicesPerDayAsync(servicesSuppliedId, dealershipId);
            if (services.ServicesPerDay==1)
            {
                foreach (var item in list)
                {
                    days.Add(item.ScheduleDay);
                }
            }
            if (list.Count > 0)
            {
                int count = 1;
                for (int i = 1; i < list.Count; i++)
                {
                    if (list[i].ScheduleDay == list[i - 1].ScheduleDay)
                    {
                        count += 1;
                        if (count == services.ServicesPerDay)
                        {
                            days.Add(list[i].ScheduleDay);
                            count = 1;
                        }
                    }
                }

                return days;
            }

            return days;

        }

        [Authorize(Roles = "Employee/Management, Employee/Reception, Admin, Customer")]
        public async Task<IActionResult> EditSchedule(int? id)
        {


            var userName = this.User.Identity.Name;

            var user = await _userHelper.GetUserByEmailAsync(userName);


            if (user.IsActive == false)
            {
                return RedirectToAction("EditUser", "Accounts");
            }

            if (id == null)
            {
                return NotFound();
            }

            var activeScheduleId = id.Value;

            var result = await _activeScheduleRepository.ExistsAsync(activeScheduleId);

            if (!result)
            {
                return View();
            }

            var scheduleDetail = await _scheduleDetailRepository.GetScheduleDetailAsync(activeScheduleId);




            var list = await GetDisabledDaysAsync(scheduleDetail.ActiveSchedule.Services.Id, scheduleDetail.Dealership.Id);

            var services = _servicesSuppliedRepository.GetWithServicesByDealershipId(scheduleDetail.Dealership.Id);

            var model = _converterHelper.ToEditScheduleViewModel(scheduleDetail, services);

            var days = Newtonsoft.Json.JsonConvert.SerializeObject(list);
            model.DaysToDisable = days;
            model.ActiveScheduleId = activeScheduleId;

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> EditSchedule(EditScheduleViewModel model)

AutoRepairShop.Web/Views/ScheduleDetails/BeginNew.cshtml
@model AutoRepairShop.Web.Models.ActiveScheduleViewModel.BeginScheduleViewModel
@{
    ViewData["Title"] = "Create Schedule";
}


@if (ViewBag.ServiceDuplicated != null)
{
    <div style="text-align: center">
        <span class="text-danger">@ViewBag.ServiceDuplicated</span>
    </div>
}


@if (ViewBag.NoVehicles != null)
{

    <div style="text-align: center">
        <h1 style="font-size: 90px">You have no cars on yout list</h1>
        <span style="font-size: 20px">Add one now</span>
        <div>
            <input type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" value="Go" onclick="location.href='@Url.Action("AddVehicle", "Vehicles")'" />
        </div>
    </div>

}
else
{

    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <div class="panel-body">
                    <form method="post">
                        <div class="form-group">
                            <label class="col-md-3 control-label" asp-for="VehicleId"></label>
                            <div class="col-md-6">
                                <select class="form-control" id="vehicles" asp-items="Model.Vehicles" asp-for="VehicleId">
                                </select>
                                <span asp-validation-for="VehicleId" class="text-danger"></span>
                            </div>

                        </div>



                        <div class="form-group">
                            <label class="col-md-3 control-label" asp-for="ServicesSuppliedId"></label>
                            <div class="col-md-6">
                                <select class="form-control" id="services" asp-items="Model.ServicesSupplied" asp-for="ServicesSuppliedId">
                                </select>
                                <span asp-validation-for="ServicesSuppliedId" class="text-danger"></span>
                            </div>

                        </div>


                        <div class="form-group">
                            <label class="col-md-3 control-label" asp-for="DealershipId"></label>
                            <div class="col-md-6">
                                <div class="selectChange">
                                    <select class="form-control" id="dealerships" asp-for="DealershipId">
                                    </select>
                                </div>
                                <span asp-validation-for="DealershipId" class="text-danger"></span>
                            </div>
                        </div>


                        <div style="text-align: center">
                            <div class="form-group">
                                <button type="submit" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">Continue</button>
                            </div>
                        </div>

                    </form>


                </div>
            </section>
        </div>
    </div>











}



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function () {
            document.getElementById("services").addEventListener("change", addActivityItem, false);

        });


    </script>


    <script type="text/javascript">
        function addActivityItem() {
            $("#dealerships").empty();
                 $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetDealershipByService")',
                    dataType: 'json',
                    data: { serviceId: $("#services").val() },

                     success: function (dealerships) {
                         $("#dealerships").append('<option value="'
                             + 0 + '">'
                             + "Select a Dealership" + '</option>');
                         $.each(dealerships, function (i, dealership) {

                             $("#dealerships").append('<option value="'
                                 + dealership.dealership.id + '">'
                                 + dealership.dealership.dealerShipName + '</option>');
                         });

                    },
                    error: function (ex) {

                        alert('failed to retrieve information try again latter');
                     },


                 })
        }

    </script>
 



}

AutoRepairShop.Web/Views/ScheduleDetails/DeleteSchedule.cshtml
@model AutoRepairShop.Web.Models.ActiveScheduleViewModel.DeleteScheduleViewModel

@{
    ViewData["Title"] = "Delete Schedule";
}

<h3>Are you sure you want to delete this?</h3>


<h2>@ViewBag.Error </h2>



<section class="panel">
    <div class="panel-body tab-content">
        <div id="access-log" class="tab-pane active">
            <table class="table table-striped table-no-more table-bordered  mb-none">
                <thead>
                    <tr>
                        <th style="width: 25%; margin: auto"><span class="text-normal text-sm">Data</span></th>
                        <th style="width: 55%"><span class="text-normal text-sm">Schedule Information</span></th>
                        @*<th style="width: 35%"><span class="text-normal text-sm">Message</span></th>*@
                    </tr>
                </thead>
                <tbody class="log-viewer">
                    <tr>
                        <td data-title="Type" class="pt-md pb-md">
                            @Html.DisplayNameFor(model => model.LicencePLate)
                        </td>
                        <td data-title="Date" class="pt-md pb-md">
                            @Html.DisplayFor(model => model.LicencePLate)
                        </td>
                    </tr>
                    <tr>
                        <td data-title="Type" class="pt-md pb-md">
                            @Html.DisplayNameFor(model => model.Dealership)
                        </td>
                        <td data-title="Date" class="pt-md pb-md">
                            @Html.DisplayFor(model => model.Dealership)
                        </td>
                    </tr>
                    <tr>
                        <td data-title="Type" class="pt-md pb-md">
                            @Html.DisplayNameFor(model => model.Service)
                        </td>
                        <td data-title="Date" class="pt-md pb-md">
                            @Html.DisplayFor(model => model.Service)
                        </td>
                    </tr>
                    <tr>
                        <td data-title="Type" class="pt-md pb-md">
                            @Html.DisplayNameFor(model => model.ScheduleDay)
                        </td>
                        <td data-title="Date" class="pt-md pb-md">
                            @Html.DisplayFor(model => model.ScheduleDay)
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <form asp-action="DeleteSchedule" style="text-align: center">
            <input type="hidden" asp-for="ActiveScheduleId" />
            <button asp-action="DeleteSchedule" asp-controller="ScheduleDetails" asp-route-id="ActiveScheduleId" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Delete</button>
            <button asp-action="ShowScheduleFordealership" formnovalidate class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Exit</button>
        </form>
    </div>

</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoRepairShop.Web/Views/ScheduleDetails/DeleteScheduleDealership.cshtml
@model AutoRepairShop.Web.Models.ActiveScheduleViewModel.DeleteScheduleViewModel

@{
    ViewData["Title"] = "Delete Schedule";
}

<h3>Are you sure you want to delete this?</h3>


<h2>@ViewBag.Error </h2>



<section class="panel">
    <div class="panel-body tab-content">
        <div id="access-log" class="tab-pane active">
            <table class="table table-striped table-no-more table-bordered  mb-none">
                <thead>
                    <tr>
                        <th style="width: 25%; margin: auto"><span class="text-normal text-sm">Data</span></th>
                        <th style="width: 55%"><span class="text-normal text-sm">Schedule Information</span></th>
                        @*<th style="width: 35%"><span class="text-normal text-sm">Message</span></th>*@
                    </tr>
                </thead>
                <tbody class="log-viewer">
                    <tr>
                        <td data-title="Type" class="pt-md pb-md">
                            @Html.DisplayNameFor(model => model.LicencePLate)
                        </td>
                        <td data-title="Date" class="pt-md pb-md">
                            @Html.DisplayFor(model => model.LicencePLate)
                        </td>
                    </tr>
                    <tr>
                        <td data-title="Type" class="pt-md pb-md">
                            @Html.DisplayNameFor(model => model.Dealership)
                        </td>
                        <td data-title="Date" class="pt-md pb-md">
                            @Html.DisplayFor(model => model.Dealership)
                        </td>
                    </tr>
                    <tr>
                        <td data-title="Type" class="pt-md pb-md">
                            @Html.DisplayNameFor(model => model.Service)
                        </td>
                        <td data-title="Date" class="pt-md pb-md">
                            @Html.DisplayFor(model => model.Service)
                        </td>
                    </tr>
                    <tr>
                        <td data-title="Type" class="pt-md pb-md">
                            @Html.DisplayNameFor(model => model.ScheduleDay)
                        </td>
                        <td data-title="Date" class="pt-md pb-md">
                            @Html.DisplayFor(model => model.ScheduleDay)
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <form asp-action="DeleteSchedule" style="text-align: center">
            <input type="hidden" asp-for="ActiveScheduleId" />
            <button asp-action="DeleteScheduleDealership" asp-controller="ScheduleDetails" asp-route-id="ActiveScheduleId" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Delete</button>
            <button asp-action="ShowScheduleForDealership" asp-controller="ScheduleDetails" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Exit</button>
        </form>
    </div>

</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoRepairShop.Web/Views/ScheduleDetails/EditSchedule.cshtml
@model AutoRepairShop.Web.Models.ActiveScheduleViewModel.EditScheduleViewModel
@{
    ViewData["Title"] = "Edit Schedule";
}





<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <div class="panel-body">
                <form method="post">
                    <input type="hidden" asp-for="ActiveScheduleId" />
                    <input type="hidden" asp-for="DaysToDisable" id="selectDate"/>
                    <div class="form-group">
                        <label class="col-md-3 control-label" asp-for="LicencePlate"></label>
                        <div class="col-md-6">
                            <input type="text"  id="inputReadOnly" class="form-control" readonly="readonly" asp-for="LicencePlate">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" asp-for="Dealership"></label>
                        <div class="col-md-6">
                            <input type="text"  id="inputReadOnly" class="form-control" readonly="readonly" asp-for="Dealership">
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="col-md-3 control-label" asp-for="ServicesSupliedId"></label>
                        <div class="col-md-6">
                            <select class="form-control" id="services" asp-items="Model.Services" asp-for="ServicesSupliedId">
                            </select>
                            <span asp-validation-for="ServicesSupliedId" class="text-danger"></span>
                        </div>

                    </div>


                    <div class=" control-section" style="text-align: center">
                        <div id="wrapper" class="datepicker-section">
                            <label asp-for="Day">Chose a Day</label>
                            <div id="datepicker-control" style="width: 250px; margin-left: 35%">
                                <ejs-datepicker id="datepicker" ejs-for="Day" renderDayCell="disableDate" min="@DateTime.Now"></ejs-datepicker>
                            </div>
                        </div>
                    </div>

                    <script>

                        function disableDate(args) {


                            if (args.date.getDay() === 0) {
                                args.isDisabled = true;
                            }
                            if (args.date.getDay() === 6) {
                                args.isDisabled = true;
                            }



                            var list = document.getElementById("selectDate").value;
                            var result = JSON.parse(list);
                            for (var i = 0; i < result.length; i++) {
                                var date = new Date(result[i]);
                                if (args.date.getDate() == date.getDate()) {
                                    args.isDisabled = true;
                                }
                            }

                        }


                    </script>

                    <div class="form-group">
                        <label class="col-md-3 control-label" asp-for="Remarks"></label>
                        <div class="col-md-6">
                            <textarea class="form-control" rows="3" data-plugin-maxlength maxlength="500" asp-for="Remarks"></textarea>
                            <p>
                                <code>max-length</code> set to 500.
                            </p>
                        </div>
                    </div>


                    <div style="text-align: center">
                        <div class="form-group">
                            <button type="submit" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Change</button>
                            @if (!this.User.IsInRole("Customer"))
                            {
                                <button asp-action="ShowScheduleForDealership" asp-controller="ScheduleDetails" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Exit</button>
                            }
                            else
                            {
                                <button asp-action="Index" asp-controller="ScheduleDetails" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Exit</button>
                            }

                            <button asp-action="DeleteSchedule" asp-controller="ScheduleDetails" asp-route-id="ActiveScheduleId" type="submit" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary" style="width: 200px">Delete Schedule</button>
                        </div>
                    </div>

                </form>


            </div>
        </section>
    </div>
</div>
<ejs-scripts></ejs-scripts>